apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  namespace: dev-envi-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: tomcat-nginix
      labels:
        app: tomcat
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: size
                  operator: NotIn
                  values:
                    - small
                    - large
      containers:
        - name: tomcat
          image: prajwal1327/mytomcat:1.1.6
